export const mockReviews = [
  {
    id: 1,
    companyName: "会社A",
    leadership: 8,
    communication: 7,
    fairness: 9,
    employee_development: 6,
    decision_making: 8,
    team_building: 7,
    emotional_management: 8,
    positives: "Great at motivating the team and setting clear goals.",
    improvements: "Could improve on providing more frequent feedback.",
    specific_episodes: "Handled a difficult client situation very professionally.",
    created_at: "2023-05-01T10:00:00Z",
  },
  {
    id: 2,
    companyName: "会社B",
    leadership: 9,
    communication: 8,
    fairness: 8,
    employee_development: 7,
    decision_making: 9,
    team_building: 8,
    emotional_management: 7,
    positives: "Excellent strategic thinking and problem-solving skills.",
    improvements: "Could delegate tasks more effectively.",
    specific_episodes: "Led a successful project launch under tight deadlines.",
    created_at: "2023-05-15T14:30:00Z",
  },
  {
    id: 3,
    companyName: "会社A",
    leadership: 7,
    communication: 8,
    fairness: 7,
    employee_development: 8,
    decision_making: 7,
    team_building: 9,
    emotional_management: 8,
    positives: "Strong focus on team development and growth.",
    improvements: "Communication could be more transparent.",
    specific_episodes: "Implemented successful mentoring program.",
    created_at: "2023-06-01T09:00:00Z",
  },
]

export const mockUser = {
  id: "1",
  username: "demo_user",
  email: "demo@example.com",
  // 他のフィールドがあれば追記
};

